# Generated by Django 2.2.5 on 2022-07-12 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20220711_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
